### ISSUE TITLE
initial prototype issues

### ISSUE THREAD

**Issue by sheikhmousa1998** [mattcuento/csc308outdoors#1]
We see that the UI pages are designed well and up to par with the storyboard concepts. Upon running the prototype, however, it was discovered that the pages were not linked to each other. We also noticed that there isn't a home page. There also does not exist a leaderboard, or messaging pages that were requested by section 02.

**Comment by zoedrewery** [comment]
> We see that the UI pages are designed well and up to par with the storyboard concepts. Upon running the prototype, however, it was discovered that the pages were not linked to each other. We also noticed that there isn't a home page. There also does not exist a leaderboard, or messaging pages that were requested by section 02.

From what we can see thus far, there also needs to be a link to the home page from the various other screens in the app.

**Comment by sjackson15** [comment]
The search screen needs a filter option for the list of trails
