### ISSUE TITLE
Fetch hard coded data from Express to List View (Connecting React Native to Express)

### ISSUE THREAD

**Issue by oshorab** [mattcuento/csc308outdoors#21]

**Comment by oshorab** [comment]
Look into using fetch and render to replace hard coded hike data in ListView.js. Figure out how to put this data into express.

**Comment by oshorab** [comment]
Estimated time: ~5hrs

**Comment by mattcuento** [comment]
API is being called correctly, fetch call works, just need to figure out how to set state on components for React Native

**Comment by oshorab** [comment]
Task not fully completed. Fetch call works, as seen while testing through Postman. However, there were issues with figuring out how to fetch hard coded JSON data.

**Comment by oshorab** [comment]
Solved using axios instead of fetch
