### ISSUE TITLE
Prototype Testing

### ISSUE THREAD

**Issue by rngage** [mattcuento/csc308outdoors#30]
Login page complete and clickable, but not yet functional (doesn't lead anywhere)
Navigation bar fully functional
List page partially complete, clickable, not yet functional 
Map page incomplete 
Stat tracker partially complete
Profile page mostly complete

**Comment by ncpalmie** [comment]
Login page now leads to list view after authentication.
List page completion, map, stat tracker, and profile pages will be addressed in future sprints.
