### ISSUE TITLE
list of popular hikes/activities

### ISSUE THREAD

**Issue by ifarrell12** [mattcuento/csc308outdoors#6]
User story 4, 3, I  As an extroverted hiker, I want to know which hikes are the most popular so that I can meet new people on the trail. There is no page that lists the popularity of activities/hikes to fulfill this user story.  Is this something that can be added or should we remove the user story?

**Comment by mattcuento** [comment]
Hey, on the hike detail pages we were hoping to use the stars shown as a system of popularity, would that be good?
