### ISSUE TITLE
hike/activity planning 

### ISSUE THREAD

**Issue by ifarrell12** [mattcuento/csc308outdoors#7]
User Story 5, 2, I  As an avid user, I want to be able to plan my trips, so that I have an organized itinerary for my trips. Are we scrapping this idea or is trip planning going to be integrated in the messaging feature?

**Comment by mattcuento** [comment]
Our team was thinking the opposite. we like the trip planning aspect but it would need to be implemented much much farther down the line, but we were planning on cutting the messaging.
